export interface Education {
  id: string;
  college: string; // Compulsory: College / University name
  degree: string;  // e.g. B.Tech Computer Science
  cgpa: string;    // Compulsory: CGPA or GPA
  gradYear: string;// e.g. 2025
  location?: string;
}

export interface WorkExperience {
  id: string;
  company: string;   // Optional section: Company worked at
  role: string;      // Designation / Title
  duration: string;  // e.g. May 2024 - Aug 2024
  location?: string;
  bullets: string[]; // Points of what you did in company (AI polishable)
}

export interface Project {
  id: string;
  title: string;        // Compulsory: Project name
  techStack: string;    // e.g. React, Next.js, Node.js, PostgreSQL
  liveUrl?: string;     // Optional
  githubUrl?: string;   // Optional
  bullets: string[];    // Compulsory points of what was built (AI polishable)
}

export interface SkillCategory {
  category: string;     // e.g. "Languages", "Frameworks & Libraries", "Developer Tools"
  skills: string[];
}

export interface ResumeData {
  // Personal Information
  name: string;             // Compulsory
  title: string;            // Current title or target designation (e.g. "Full Stack Engineer")
  email: string;            // Compulsory
  phone: string;            // Compulsory
  linkedin: string;         // Compulsory
  github?: string;          // Optional
  website?: string;         // Optional
  location?: string;
  summary?: string;         // Professional summary (can be generated by AI)

  // Education (Compulsory College & CGPA)
  education: Education[];

  // Work Experience (Optional)
  experience: WorkExperience[];

  // Personal Projects (Compulsory)
  projects: Project[];

  // Skills
  skills: SkillCategory[];
}

export type TemplateId =
  | "cupertino-modern"
  | "minimal-ats"
  | "tech-innovator"
  | "executive-serif"
  | "creative-dev"
  | "elegant"
  | "compact"
  | "bold"
  | "professional"
  | "clean";

export interface TemplateOption {
  id: TemplateId;
  name: string;
  description: string;
  badge: string;
}
